name = "code-sharing-hono"
main = "src/index.ts"
compatibility_date = "2024-10-05"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "code-sharing-hono"
# database_id = "79c95b1d-946e-4758-8a5d-2f5fc6b6be30"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1